### ISSUE TITLE
Version 1.1 breaks for larger builds

### ISSUE THREAD

**Issue by specimen151** [mariocasciaro/gulp-clone#7] opened 2018-01-10 09:49 UTC
FYI:
After the new version came 7-8 days ago, Semantic-UI won't build any more. Of course that is an issue for that project, but I'm letting you know in case there is some underlying issue with the new version of gulp-clone. From what I've seen it it seems the size have something to do with it (if I build a larger stream/clone... don't know the term... then it crashes).

Noticed that some underlying dependencies have changed, and maybe there are some limitations on them.

https://github.com/Semantic-Org/Semantic-UI/issues/6067

**Comment by gardner** [comment] 2018-01-12 01:01
Is this closed as fixed, or unable to reproduce, or out of scope? Thanks

**Comment by specimen151** [comment] 2018-01-12 08:53
I could not find the delete button, so I closed it. Could be the other project is using gulp-clone wrong, I really don't know, so I changed my mind and wanted to delete the issue from gulp-clone. It has been working (and still is) with 1.0.0 though.

**Comment by jayphelps** [comment] 2018-01-12 20:45
Can this ticket be reopened or should I make another one? https://github.com/Semantic-Org/Semantic-UI/issues/6067 is still on-going. Appears to have been caused by https://github.com/mariocasciaro/gulp-clone/commit/918beb65a74af517345db0ebe0c20497f5c0d606 so probably a difference between `gulp-util` and its replacement.

@mariocasciaro Would you accept a PR to reverts that change temporarily to release a 1.1.2 to fix things, then release the change with a 2.0.0 instead?

**Comment by mariocasciaro** [comment] 2018-01-12 21:37
Jay that sounds good to me.

On Jan 12, 2018 21:02, "Jay Phelps" <notifications@github.com> wrote:

Can this ticket be reopened or should I make another one?
Semantic-Org/Semantic-UI#6067
<https://github.com/Semantic-Org/Semantic-UI/issues/6067> is still
on-going. Appears to have been caused by 918beb6
<https://github.com/mariocasciaro/gulp-clone/commit/918beb65a74af517345db0ebe0c20497f5c0d606>
so probably a difference between gulp-util or vinyl and their replacements.

@mariocasciaro <https://github.com/mariocasciaro> Would you accept a PR to
reverts that change temporarily to release a 1.1.2 to fix things, then
release the change with a 2.0.0 instead?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mariocasciaro/gulp-clone/issues/7#issuecomment-357349159>,
or mute the thread

**Comment by mariocasciaro** [comment] 2018-01-15 16:41
Done. 
1.1.2 now contains the 1.0.0 code. 
2.0.0 now contains the new version which drops the dependency on gutils.

**Closed by mariocasciaro** 2018-01-15 16:41 UTC

**Comment by jayphelps** [comment] 2018-01-15 18:56
@mariocasciaro thank you! 🍻
